### ISSUE TITLE
在自定义View里使用，布局不能预览

### ISSUE THREAD

**Issue by SelectSex** [JeremyLiao/LiveEventBus#148]
## 描述 Bug

自定义view中调用了LiveEventBus.get<Int>方法，无法预览， 
- 库 的版本：1.8.0
- 出现 Bug 的设备型号： studio直接预览报错
- 设备的 Android 版本：项目编译sdk api 30

## 相关代码

```
    override fun onAttachedToWindow() {
        super.onAttachedToWindow()
        LiveEventBus.get<Int>(EventKeys.Bet_Click_Parlay_Refresh).observeForever(updataUi)
        GlobalRequest.getMemberBalance.observeForever(getMemberBalance)
    }
```

## 异常堆栈
```
java.lang.NullPointerException   at java.lang.reflect.Method.invoke(Method.java:559)
   at com.jeremyliao.liveeventbus.utils.AppUtils.getApplicationByReflect(AppUtils.java:98)
   at com.jeremyliao.liveeventbus.utils.AppUtils.getApp(AppUtils.java:88)
   at com.jeremyliao.liveeventbus.core.LiveEventBusCore.registerReceiver(LiveEventBusCore.java:123)
   at com.jeremyliao.liveeventbus.core.LiveEventBusCore.<init>(LiveEventBusCore.java:83)
   at com.jeremyliao.liveeventbus.core.LiveEventBusCore.<init>(LiveEventBusCore.java:38)
   at com.jeremyliao.liveeventbus.core.LiveEventBusCore$SingletonHolder.<clinit>(LiveEventBusCore.java:44)
   at com.jeremyliao.liveeventbus.core.LiveEventBusCore.get(LiveEventBusCore.java:48)
   at com.jeremyliao.liveeventbus.LiveEventBus.get(LiveEventBus.java:35)
   at com.jeremyliao.liveeventbus.LiveEventBus.get(LiveEventBus.java:46)
   at com.android.orange_android.widget.BetTopTitleView.onAttachedToWindow(BetTopTitleView.kt:159)
```

## 截图
![image](https://user-images.githubusercontent.com/90268640/141336980-7242aa64-ee08-4013-8e61-cea957c0752a.png)
简单报错
![image](https://user-images.githubusercontent.com/90268640/141337183-415569b2-c28e-4e26-ab2b-47dd991ce470.png)
具体详细错误
![image](https://user-images.githubusercontent.com/90268640/141337314-cc778fca-a331-4cc0-b181-aae8d99e498d.png)

## 分析
在此处调用invoke，会在自定义view中预览时抛出Null异常。

![image](https://user-images.githubusercontent.com/90268640/141337846-7d362055-83f8-44d1-9f4b-27fb0fb0a78f.png)

invoke 方法会报错

![image](https://user-images.githubusercontent.com/90268640/141336363-d52e6e08-350c-4beb-b22f-a91a4b420f90.png)

报错后未try catch 

![image](https://user-images.githubusercontent.com/90268640/141337945-ae794f07-7208-4685-946e-32b2f1d4f673.png)

**Comment by SelectSex** [comment]
[live_event_bug_x1.8.0.zip](https://github.com/JeremyLiao/LiveEventBus/files/7526215/live_event_bug_x1.8.0.zip)
将我正在用的1.8.0都aar反编译修改了 getApplicationByReflect方法，引入项目，预览终于正常了
我修改的代码并不会对app运行时造成错误，只是修改了npe异常的使用，好让 预览编译顺利运行下去

**Comment by Lieeber** [comment]
想预览用isInEditMode就行了。

**Comment by SelectSex** [comment]
感谢感谢，太谢谢了，好几年的开发了，这个属性都没注意过！

Barry Lee ***@***.***> 于 2022年1月4日周二 下午5:48写道：
