### ISSUE TITLE
android.os.TransactionTooLargeException: data parcel size 2600612 bytes

### ISSUE THREAD

**Issue by IdioticMadman** [JeremyLiao/LiveEventBus#150]
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2600612 bytes
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1131)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:468)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at com.jeremyliao.liveeventbus.core.LiveEventBusCore$LiveEvent.broadcastInternal(LiveEventBusCore.java:383)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at com.jeremyliao.liveeventbus.core.LiveEventBusCore$LiveEvent.broadcast(LiveEventBusCore.java:244)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at com.jeremyliao.liveeventbus.core.LiveEventBusCore$LiveEvent.postAcrossApp(LiveEventBusCore.java:183)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at com.jeremyliao.lebapp.LiveEventBusDemo.testBroadcast(LiveEventBusDemo.java:232)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at com.jeremyliao.lebapp.databinding.ActivityLiveDataBusDemoBindingImpl._internalCallbackOnClick(ActivityLiveDataBusDemoBindingImpl.java:321)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at com.jeremyliao.lebapp.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.view.View.performClick(View.java:7520)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.view.View.performClickInternal(View.java:7489)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.view.View.access$3600(View.java:826)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.view.View$PerformClick.run(View.java:28555)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.os.Looper.loop(Looper.java:233)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8010)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err: Caused by: android.os.TransactionTooLargeException: data parcel size 2600612 bytes
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.os.BinderProxy.transact(BinderProxy.java:591)
2021-12-28 11:42:38.574 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5680)
2021-12-28 11:42:38.575 2527-2527/com.jeremyliao.livedatabus W/System.err:     at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1126)
2021-12-28 11:42:38.575 2527-2527/com.jeremyliao.livedatabus W/System.err: 	... 18 more

**Comment by wanxiasijin** [comment]
明显跨进程你传输数据大于1M了

**Comment by IdioticMadman** [comment]
@wanxiasijin 这个不支持大数据跨进程么？

**Comment by wanxiasijin** [comment]
肯定不支持啊 
原理binder机制的  要大数据需要匿名共享内存
