### ISSUE TITLE
新系统适配

### ISSUE THREAD

**Issue by Qdafengzi** [JeremyLiao/LiveEventBus#166]
Caused by: java.lang.SecurityException: com.xxxx One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                 	at android.os.Parcel.createException(Parcel.java:3041)
                 	at android.os.Parcel.readException(Parcel.java:3024)
                 	at android.os.Parcel.readException(Parcel.java:2966)
                 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
                 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
                 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
                 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
                 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                 	at com.jeremyliao.liveeventbus.core.LiveEventBusCore.registerReceiver(LiveEventBusCore.java:126)
                 	at com.jeremyliao.liveeventbus.core.LiveEventBusCore.<init>(LiveEventBusCore.java:83)
                 	at com.jeremyliao.liveeventbus.core.LiveEventBusCore.<init>(LiveEventBusCore.java:38)
                 	at com.jeremyliao.liveeventbus.core.LiveEventBusCore$SingletonHolder.<clinit>(LiveEventBusCore.java:44)
                 	... 125 more

**Comment by michaellee123** [comment]
https://github.com/michaellee123/LiveEventBus

**Comment by jintian666666** [comment]
> https://github.com/michaellee123/LiveEventBus

怎么有依赖冲突~
