### ISSUE TITLE
魅族手机报错

### ISSUE THREAD

**Issue by 157821** [JeremyLiao/LiveEventBus#170]
java.lang.ExceptionInInitializerError
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore.get(LiveEventBusCore.java:48)
	at com.jeremyliao.liveeventbus.LiveEventBus.get(LiveEventBus.java:35)
	at com.jeremyliao.liveeventbus.LiveEventBus.get(LiveEventBus.java:46)
	at com.biya.authenticator.ui.activity.MainActivity.observeLiveEventBus(MainActivity.kt:31)
	at com.biya.authenticator.base.BaseViewBindingActivity.onCreate(BaseViewBindingActivity.kt:84)
	at android.app.Activity.performCreate(Activity.java:8647)
	at android.app.Activity.performCreate(Activity.java:8625)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1462)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3977)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2485)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8358)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
Caused by: java.lang.SecurityException: com.biya.authenticator: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5722)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1857)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1797)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1785)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore.registerReceiver(LiveEventBusCore.java:127)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore.<init>(LiveEventBusCore.java:83)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore.<init>(LiveEventBusCore.java:38)
	at com.jeremyliao.liveeventbus.core.LiveEventBusCore$SingletonHolder.<clinit>(LiveEventBusCore.java:44)
	... 21 more

**Comment by svtar** [comment]
我遇到同样的问题，请问你怎么解决的？

**Comment by SomeHardWorker** [comment]
我也遇到了，请问你们解决了吗？

**Comment by 157821** [comment]
implementation 'com.github.michaellee123:LiveEventBus:1.8.14'




| |
李胜博
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Some Hard ***@***.***> |
| 发送日期 | 2024年3月27日 14:56 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [JeremyLiao/LiveEventBus] 魅族手机报错 (Issue #170) |

我也遇到了，请问你们解决了吗？

**Comment by 157821** [comment]
com.github.michaellee123:LiveEventBus:1.8.14

**Comment by 157821** [comment]
com.github.michaellee123:LiveEventBus:1.8.14  





| |
huoxu
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Some Hard ***@***.***> |
| 发送日期 | 2024年3月27日 14:56 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [JeremyLiao/LiveEventBus] 魅族手机报错 (Issue #170) |

我也遇到了，请问你们解决了吗？

**Comment by 157821** [comment]
解决办法 引用 com.github.michaellee123:LiveEventBus:1.8.14

**Comment by ChenBabys** [comment]
> 解决办法 引用 com.github.michaellee123:LiveEventBus:1.8.14

你这个库会一直保持有效吗

**Comment by encyclist** [comment]
三星平板也遇到了同样的问题
