### ISSUE TITLE
跨进程通信的错误以及解决办法

### ISSUE THREAD

**Issue by liangchaojie** [JeremyLiao/LiveEventBus#81]
Caused by: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.douyu.yuba.bean.BasePostNews)

java.lang.RuntimeException: Error receiving broadcast Intent { act=intent.action.ACTION_LEB_IPC flg=0x80010 (has extras) } in com.jeremyliao.liveeventbus.ipc.receiver.LebIpcReceiver@9449453

错误原因:
斗鱼也使用了LiveDataBus然后跨进程发送了一个序列化的event事件，你的进程捕获到了这个事件但是无法解析这个类，所以报异常

解决办法:
如果你的进程只支持单进程的话
 LiveEventBus.get()
                .config()
                //supportBroadcast  是否支持跨进程,目前只使用单进程不接收其他应用广播
               // .supportBroadcast(realApplication)
                // lifecycleObserverAlwaysActive false的时候表示页面可见才能收到消息通知，不可见不处理消息
                .lifecycleObserverAlwaysActive(false)
                .autoClear(false);

如果你本身就需要用到多进程的话，如何解决？

**Comment by JeremyLiao** [comment]
你指的是这个bean（com.douyu.yuba.bean.BasePostNews）在你的应用里面本身就是不存在的吗？这样可能会报错。麻烦贴下完整的堆栈信息

**Comment by liangchaojie** [comment]
对的  我的项目不存在这个bean类

`java.lang.RuntimeException: Error receiving broadcast Intent { act=intent.action.ACTION_LEB_IPC flg=0x80010 (has extras) } in com.jeremyliao.liveeventbus.ipc.receiver.LebIpcReceiver@9449453
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_56045(LoadedApk.java:1420)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:200)
	at android.app.ActivityThread.main(ActivityThread.java:7046)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:521)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
Caused by: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.douyu.yuba.bean.BasePostNews)
	at android.os.Parcel.readSerializable(Parcel.java:3035)
	at android.os.Parcel.readValue(Parcel.java:2821)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3139)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
	at android.os.BaseBundle.unparcel(BaseBundle.java:226)
	at android.os.BaseBundle.getString(BaseBundle.java:1124)
	at android.content.Intent.getStringExtra(Intent.java:7187)
	at com.jeremyliao.liveeventbus.ipc.receiver.LebIpcReceiver.onReceive(SourceFile:23)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_56045(LoadedApk.java:1403)
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.douyu.yuba.bean.BasePostNews
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at android.os.Parcel$2.resolveClass(Parcel.java:3021)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1616)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1777)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1354)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:374)
	at android.os.Parcel.readSerializable(Parcel.java:3029)
	... 17 more
Caused by: java.lang.ClassNotFoundException: Didn&#39;t find class &quot;com.douyu.yuba.bean.BasePostNews&quot; on path: DexPathList[[zip file &quot;/data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/base.apk&quot;],nativeLibraryDirectories=[/data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/lib/arm, /data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 26 more
java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.douyu.yuba.bean.BasePostNews)
	at android.os.Parcel.readSerializable(Parcel.java:3035)
	at android.os.Parcel.readValue(Parcel.java:2821)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3139)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
	at android.os.BaseBundle.unparcel(BaseBundle.java:226)
	at android.os.BaseBundle.getString(BaseBundle.java:1124)
	at android.content.Intent.getStringExtra(Intent.java:7187)
	at com.jeremyliao.liveeventbus.ipc.receiver.LebIpcReceiver.onReceive(SourceFile:23)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_56045(LoadedApk.java:1403)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:200)
	at android.app.ActivityThread.main(ActivityThread.java:7046)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:521)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
Caused by: java.lang.ClassNotFoundException: com.douyu.yuba.bean.BasePostNews
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at android.os.Parcel$2.resolveClass(Parcel.java:3021)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1616)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1777)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1354)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:374)
	at android.os.Parcel.readSerializable(Parcel.java:3029)
	... 17 more
Caused by: java.lang.ClassNotFoundException: Didn&#39;t find class &quot;com.douyu.yuba.bean.BasePostNews&quot; on path: DexPathList[[zip file &quot;/data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/base.apk&quot;],nativeLibraryDirectories=[/data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/lib/arm, /data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 26 more
java.lang.ClassNotFoundException: com.douyu.yuba.bean.BasePostNews
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at android.os.Parcel$2.resolveClass(Parcel.java:3021)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1616)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1777)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1354)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:374)
	at android.os.Parcel.readSerializable(Parcel.java:3029)
	at android.os.Parcel.readValue(Parcel.java:2821)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3139)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
	at android.os.BaseBundle.unparcel(BaseBundle.java:226)
	at android.os.BaseBundle.getString(BaseBundle.java:1124)
	at android.content.Intent.getStringExtra(Intent.java:7187)
	at com.jeremyliao.liveeventbus.ipc.receiver.LebIpcReceiver.onReceive(SourceFile:23)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_56045(LoadedApk.java:1403)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:200)
	at android.app.ActivityThread.main(ActivityThread.java:7046)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:521)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
Caused by: java.lang.ClassNotFoundException: Didn&#39;t find class &quot;com.douyu.yuba.bean.BasePostNews&quot; on path: DexPathList[[zip file &quot;/data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/base.apk&quot;],nativeLibraryDirectories=[/data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/lib/arm, /data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 26 more
java.lang.ClassNotFoundException: Didn&#39;t find class &quot;com.douyu.yuba.bean.BasePostNews&quot; on path: DexPathList[[zip file &quot;/data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/base.apk&quot;],nativeLibraryDirectories=[/data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/lib/arm, /data/app/reader.com.xmly.xmlyreader-K4ivsp4sifFA34RpsKphPA==/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at android.os.Parcel$2.resolveClass(Parcel.java:3021)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1616)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1777)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1354)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:374)
	at android.os.Parcel.readSerializable(Parcel.java:3029)
	at android.os.Parcel.readValue(Parcel.java:2821)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3139)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:273)
	at android.os.BaseBundle.unparcel(BaseBundle.java:226)
	at android.os.BaseBundle.getString(BaseBundle.java:1124)
	at android.content.Intent.getStringExtra(Intent.java:7187)
	at com.jeremyliao.liveeventbus.ipc.receiver.LebIpcReceiver.onReceive(SourceFile:23)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_56045(LoadedApk.java:1403)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:200)
	at android.app.ActivityThread.main(ActivityThread.java:7046)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:521)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)`

**Comment by JeremyLiao** [comment]
我试了一下，对于这种问题，最新版可以catch住，不会crash，你可以试下：1.5.4

**Comment by liangchaojie** [comment]
@JeremyLiao 

我项目没有用到多进程，所以的话我把支持多进程通信给禁止了
这应该就可以不让自己的项目捕获其他应用的event进而造成解析失败报异常了
可是我担心以后项目要支持多进程通信，咱们的LiveDataBus能够区分哪些进程是我要进行通讯的？
可以过滤掉那些不是自己想要的event吗？

我们可以进一步聊吗，能不能给我个好友位   微信 LG06180214

**Comment by JeremyLiao** [comment]
没有开启支持多进程是没有问题的。如果使用跨进程，在最新版上也不会crash，因为这个功能就是用于跨进程、跨APP通信的，所以不想收到消息的话，设置不同的key就可以了。

**Comment by liangchaojie** [comment]
使用最新版本解决问题
